[project]
name = "RecoverFit"
version = "1.0.0"
description = "Aplicacion de gestion de pagos y clientes para RecoverFit"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "mauro_dev" }
]
dependencies = [
    "flet==0.85.2",
    "SQLAlchemy",
    "python-dateutil",
]

[project.optional-dependencies]
dev = [
    "flet-cli==0.85.2",
    "flet-desktop==0.85.2",
    "flet-web==0.85.2",
]

[tool.flet]
org = "com.recoverfit"
product = "gestion RecoverFit"
company = "RecoverFit"
copyright = "Copyright (C) 2023-2026"
assets_dir = "src/assets"

[tool.flet.app]
path = "src"
