[project]
name = "gestion-pagos"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Flet developer", email = "you@example.com" }
]
dependencies = [
    "flet>=0.85.2"
]

[dependency-groups]
dev = [
    "flet-cli>=0.85.2",
    "flet-desktop>=0.85.2",
    "flet-web>=0.85.2",
]

[tool.flet]
org = "com.mycompany"
product = "gestion-pagos"
company = "Flet"
copyright = "Copyright (C) 2023-2026 by Flet"
# opcion especial para linux
# tipos ligth (es nativa de linux no soporta audios y videos) y full si soporta audios y videos
desktop_flavor = "light"

[tool.flet.app]
path = "src"
